In [1]:
import numpy as np

A = np.array([[0,1], [-1,0]])

b = np.array([2,2])

np.linalg.norm(b)

2.8284271247461903

In [2]:
np.linalg.norm(A@b)

2.8284271247461903

In [8]:
import scipy.linalg 
A = np.array([[2,4,-2],[-2,-3,7],[3,9,-4],[]])


a,b, c = scipy.linalg.lu(A)

In [14]:
A = np.array([[2,4,-2,2],[-2,-3,7,10],[3,9,-4,7]])
A

array([[ 2,  4, -2,  2],
       [-2, -3,  7, 10],
       [ 3,  9, -4,  7]])

In [16]:
np.array([[1,0,0],[0,1,0],[0,-3,1]]) @ np.array([[1,0,0],[1,1,0],[-3/2,0,1]]) @ A

array([[  2.,   4.,  -2.,   2.],
       [  0.,   1.,   5.,  12.],
       [  0.,   0., -16., -32.]])

In [17]:
np.array([[1,0,0],[0,1,0],[0,-3,1]]) @ np.array([[1,0,0],[1,1,0],[-3/2,0,1]])

array([[ 1. ,  0. ,  0. ],
       [ 1. ,  1. ,  0. ],
       [-4.5, -3. ,  1. ]])

In [19]:
A[:,:3]

array([[ 2,  4, -2],
       [-2, -3,  7],
       [ 3,  9, -4]])

In [23]:
L = np.array([[1,0,0],[0,1,0],[0,-3,1]]) @ np.array([[1,0,0],[1,1,0],[-3/2,0,1]])

U = np.array([[1,0,0],[0,1,0],[0,-3,1]]) @ np.array([[1,0,0],[1,1,0],[-3/2,0,1]]) @ A

L@U[:,:3]



array([[  2.,   4.,  -2.],
       [  2.,   5.,   3.],
       [ -9., -21., -22.]])

In [32]:
np.linalg.inv(L) 

array([[ 1. , -0. , -0. ],
       [-1. ,  1. , -0. ],
       [ 1.5,  3. ,  1. ]])

In [29]:
L

array([[ 1. ,  0. ,  0. ],
       [ 1. ,  1. ,  0. ],
       [-4.5, -3. ,  1. ]])