# Tarea 1 - Álgebra Lineal y Optimización para Data Science

Debe entregar este Colab con sus respuestas a más tardar el día 30 de Septiembre a las 23:59 hrs, vía Webcursos. No olvide indicar los integrantes de su grupo.

**Importante**: En todas las preguntas debe utilizar NumPy y su módulo linalg, junto con funciones básicas de Python. Puede agregar celdas adicionales para hacer los tests que desee.

### Parte 1 (1.5 pts)

1. (0.5 pts) Recuerde que el _producto externo_ entre dos vectores $\bar{x}\in \mathbb{R}^n$, $\bar{y}\in \mathbb{R}^m$, denotado $\bar{x}\otimes\bar{y}$ se define como la matriz de $n\times m$:

 $$\bar{x}\otimes\bar{y}=\begin{bmatrix}
x_1 y_1 & x_1 y_2 & \cdots & x_1 y_m\\
x_2 y_1 & x_2 y_2 & \cdots & x_2 y_m\\
\vdots & \vdots & \vdots & \vdots\\
x_n y_1 & x_n y_2 & \cdots & x_n y_m\\
\end{bmatrix}$$

 Implemente una función `outer_product(x, y)` que reciba dos vectores $\bar{x}$ e $\bar{y}$, y entregue el producto externo $\bar{x}\otimes\bar{y}$.

 **Ojo**: No puede usar la función `np.linalg.outer`. 

In [3]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,2,3])

In [4]:
def outer_product(a,b):
    dim_a = len(a)
    dim_b = len(b)

    output = np.zeros((dim_a, dim_b))
    for idx_b, item_b in enumerate(b):
        for idx_a, item_a in enumerate(a):
            output[idx_a, idx_b] = item_a * item_b

    return output


assert (np.outer(a,b) == outer_product(a,b)).all() # chequeo que la función sea correcta

2. (0.5 pts) Implemente una función `outer_matrix_mul(A,B)` que reciba matrices $A$ de $n\times m$ y $B$ de $m\times p$ y entregue:

 $$A_{*,1}\otimes B_{1,*} + \cdots A_{*,m}\otimes B_{m,*}$$

 Debe utilizar su función `outer_product(x, y)`. Recuerde que esto coincide con $AB$, luego puede validar sus resultados utilizando esa equivalencia.
 
 **Ojo**: No puede usar el producto de matrices en su implementación.




In [5]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])
C = np.array([[1,2],[4,5],[6,7]])

In [6]:
def outer_matrix_mul(A,B):

    try:
        assert A.shape[1] == B.shape[0]
        dim_row = A.shape[0]
        dim_col = B.shape[1]

        output = np.zeros((dim_row, dim_col))
        for col, row in zip(A.T, B):
            output += outer_product(col, row)
        return output
    except AssertionError:
        print("Error: Las dimensiones de las matrices no son compatibles.")


assert (outer_matrix_mul(A,B) == A @ B).all() # chequeo que la función sea correcta
outer_matrix_mul(A,C) ## Debe fallar

Error: Las dimensiones de las matrices no son compatibles.


3. (0.5 pts) Sea $A$ una matriz de $n\times m$ y $B$ una matriz de $p\times q$. Se define el _producto de Kronecker_ como la matriz de $np \times mq$:

 $$A\otimes B = 
\begin{bmatrix}
A_{1,1} B & \cdots & A_{1,m} B\\
\vdots & \vdots & \vdots\\
A_{n,1} B & \cdots & A_{n,m} B\\
\end{bmatrix}$$

 Por ejemplo:
 $$
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
\otimes 
\begin{bmatrix}
0 & 5\\
6 & 7
\end{bmatrix}
=
\begin{bmatrix}
1 \begin{bmatrix}
0 & 5\\
6 & 7
\end{bmatrix} & 2 \begin{bmatrix}
0 & 5\\
6 & 7
\end{bmatrix}\\
3 \begin{bmatrix}
0 & 5\\
6 & 7
\end{bmatrix} & 4 \begin{bmatrix}
0 & 5\\
6 & 7
\end{bmatrix}
\end{bmatrix}
=
\begin{bmatrix}
0 & 5 & 0 & 10\\
6 & 7 & 12 & 14\\
0 & 15 & 0 & 20\\
18 & 21 & 24 & 28
\end{bmatrix}
$$

 $$ \begin{bmatrix}
2 & 3\\
\end{bmatrix}
\otimes 
\begin{bmatrix}
0 & 5\\
6 & 7\\
1 & -1
\end{bmatrix}
=
\begin{bmatrix}
2 \begin{bmatrix}
0 & 5\\
6 & 7\\
1 & -1
\end{bmatrix} & 3 \begin{bmatrix}
0 & 5\\
6 & 7\\
1 & -1
\end{bmatrix}\\
\end{bmatrix}
= 
\begin{bmatrix}
0 & 10 & 0 & 15\\ 
12 & 14 & 18 & 21\\
2 & -2 & 3 & -3
\end{bmatrix}
$$

 Implemente una función `kronecker(A, B)` que reciba dos matrices y entregue su producto de Kronecker.

 **Ojo**: No puede utilizar funciones de `np.linalg` que le resuelvan el problema directamente.

In [7]:
A = np.array([[1,2],[3,4]])
B = np.array([[0,5],[6,7]])
C = np.array([[2,3]])
D = np.array([[0,5],[6,7],[1,-1]])
E = np.array([2,3])


In [8]:
def kronecker(A,B):
    try:
        assert len(A.shape) > 1 and len(B.shape) > 1
        n, m = A.shape
        p, q = B.shape

        output = np.zeros((n*p, m*q))
        for i in range(n):
            for j in range(m):
                output[i*p : i*p + p, j*q : j*q + q] = A[i,j]*B

        return output
    except AssertionError:
        print("Error: Los objetos tienen que tener al menos dos dimensiones")

assert (kronecker(A,B) == np.kron(A,B)).all()
assert (kronecker(C,D) == np.kron(C,D)).all()
kronecker(E,D)


Error: Los objetos tienen que tener al menos dos dimensiones


### Parte 2 (1.5 pts)

Un _grafo (no dirigido)_ es un par $G=(V,E)$, donde $V=\{1,\dots, n\}$ es el conjunto de nodos y $E\subseteq \{\{i,j\}\mid i,j\in\{1,\dots,n\}, i\neq j\}$ el conjunto de aristas. Un _camino_ en $G$ de un nodo $i$ a un nodo $j$ es una secuencia $h_0, e_1, h_1, e_2, h_2, \dots, h_{k-1}, e_k, h_k$, para $k\geq 0$ tal que $h_0=i$, $h_k=j$ y $e_p=\{h_{p-1}, h_{p}\}\in E$, para todo $1\leq p \leq k$. El largo del camino es $k$ (es decir, la cantidad de aristas del camino). 

La _matriz de adyacencia_ $A$ de $G$ es una matriz de $n\times n$ donde $A_{i,j}=1$ si $\{i,j\}\in E$ y $A_{i,j}=0$ en caso contrario. Notar que $A$ es una matriz simétrica. 

1. (0.5 pts) Indique qué contienen las entradas de la matriz $A^2$. Argumente su respuesta. ¿Qué cree que sucede con $A^k$, para cierto $k\geq 0$?

2. (1.0 pts) Implemente una función `cantidad_triangulos(A)` que recibe la matriz de adyacencia $A$ de un grafo $G$ y retorna la cantidad de triángulos en $G$. Un _triángulo_ es un camino de largo 3 que parte y termina en el mismo nodo. Un triángulo debe contarse una sóla vez _independiente_ de su punto de partida y orientación.

 **Ojo:** Debe utilizar la pregunta anterior para su implementación.

In [9]:
def calcular_triangulos(A):
    m = A@A@A
    return np.trace(m)/6

A = np.array([[0,1,1,1],[1,0,1,0],[1,1,0,1],[1,0,1,0]])

calcular_triangulos(A)

2.0

### Parte 3 (1.0 pts)

Usando funciones de `np.linalg` implemente una función `sistema_lineal(A,b)` que reciba una matriz $A$ de $n\times m$ y un vector $\bar{b}\in \mathbb{R}^n$ tal que resuelve el sistema lineal $A\bar{x} = \bar{b}$:

- Si el sistema tiene solución entrega _alguna_ solución.
- Si el sistema no tiene solución, entrega un mensaje indicando que no hay solución.

In [10]:
## PROBLEMA CON SISTEMA SIN SOLUCIONES E INFINITAS SOLUCIONES...

def sistema_lineal(A,b):
    return np.linalg.lstsq(A,b, rcond=0.0001)

A = [[1,1],[1,1]]
b = [10,5]


sistema_lineal(A,b)

(array([3.75, 3.75]), array([], dtype=float64), 1, array([2., 0.]))

In [11]:
A = [[1,1],[2,2]]
b = [3,6]

sistema_lineal(A,b)

(array([1.5, 1.5]),
 array([], dtype=float64),
 1,
 array([3.16227766e+00, 1.57009246e-16]))

### Parte 4 (2.0 pts)

1. (1.0 pts) Implemente una función `regresion_lineal(X, y)` que recibe un conjunto de datos y entrega una solución $\bar c$ del problema de regresión lineal, junto con el error cuadrático alcanzado. Los datos son entregados como una matriz $X$ donde cada **fila** es un dato $\bar{x}_i$ y un vector $\bar{y}$ donde la coordenada i-ésima $y_i$ es el valor real asociado a $\bar{x}_i$. Para implementar `regresion_lineal(X, y)` **debe** utilizar `numpy.linalg.lstsq`. 

In [16]:
from sklearn.metrics import mean_squared_error

def regresion_lineal(X,y, add_intercept=True):
    if add_intercept:
        X = np.hstack((np.ones((X.shape[0],1)), X))
    c = np.linalg.lstsq(X,y, rcond=None)[0]
    y_pred = X@c
    mse = mean_squared_error(y, y_pred)

    return c, mse



2. (1.0 pts) Aplique su función al dataset "California housing dataset" de `scikit learn`. Para más detalles ver:

 https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html.

 ¿Cuáles son los parámetros que obtiene? ¿Cuánto es el error cuadrático alcanzado?

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import mean_squared_error
X,y = fetch_california_housing(return_X_y=True)
print(X.shape, y.shape)

c, mse = regresion_lineal(X,y)
mse

(20640, 8) (20640,)


0.5243209861846072